package com.example.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue

object Localization {
    private val translations = mapOf(
        "en" to mapOf(
            "app_title" to "Guava Mall",
            "app_subtitle" to "Fresh & Organic Smart Grocery Design",
            "app_description" to "Organic Fresh Grocery & Smart AI Shopping Platform",
            "sign_up_tab" to "إنشاء حساب (Sign Up)",
            "sign_in_tab" to "تسجيل دخول (Sign In)",
            "create_account" to "Create Your Account",
            "full_name" to "Full Name (الاسم الكامل)",
            "phone_num" to "Phone Number (رقم الهاتف)",
            "email_addr" to "Email Address (البريد الإلكتروني)",
            "select_role" to "Select App Role (اختر وظيفتك):",
            "role_customer" to "Customer",
            "role_merchant" to "Merchant",
            "role_delivery" to "Driver",
            "role_admin" to "Owner",
            "request_code" to "Request AI Access Code 🔑",
            "google_signup" to "Sign up with Google (التسجيل بجوجل)",
            "sign_in_title" to "Sign In to Your Workspace",
            "enter_email_phone" to "Email or Phone Number",
            "password" to "Password (كلمة المرور)",
            "access_platform" to "Access Platform Securely 🔑",
            "quick_fill" to "Quick Fill Default Admin Credentials (اضغط للتعبئة التلقائية)",
            "shield_sec" to "Shield Security Verified",
            "otp_msg" to "A unique 6-digit access OTP has been compiled by the AI platform security matrix and sent to your email or phone.",
            "secret_msg" to "🔑 Platform Secret Access Key: ",
            "six_digit" to "Enter 6-Digit Access Code",
            "back" to "Back",
            "confirm_access" to "Confirm Access ✔",
            "select_google_acc" to "Select google account to link",
            "google_picker_desc" to "Please select the active email linked to your device to secure access with Google OAuth integration:",
            "google_consent_title" to "Google Permission Approval",
            "google_consent_desc" to "AI Store requests access to secure authentication parameters:",
            "google_consent_bullets" to "• Verify your primary Google email\n• Sync personal profile name and photo\n• Grant secure access permission to save shopping metrics",
            "google_consent_note" to "By agreeing, Google will authorize the app client and securely sign you in.",
            "approve_connect" to "Approve & Connect 🚀",
            "deny" to "Deny",
            "cancel" to "Cancel",
            "hi" to "Hi, ",
            "logout" to "Logout",
            "ai_core" to " ACTIVE AI CORE PERSISTENCE",
            "ai_idle" to "AI is idle. Trigger any Visual Search, Price Match, Excel Alignment or Dispute Auto-Arbitration task above to initiate the intelligence engine...",
            "workspace_customer" to "Customer Workspace (بوابة المشتري الذكية)",
            "workspace_merchant" to "Merchant AI Engine (بوابة التاجر الذكية)",
            "workspace_delivery" to "Logistics Optimizer (موظف التوصيل والمسارات)",
            "workspace_admin" to "Platform Control & Audits (لوحة تحكم المالك الخاص)",
            "customer_search_title" to "🔍 Smart IA Visual Search & Compare",
            "customer_search_desc" to "Photograph or type a product name. AI instantly searches social media, registered networks, and compares retail vs carton wholesales.",
            "search_placeholder" to "E.g., wild mountain honey...",
            "map_budget_btn" to "Map Budget 💸",
            "budget_placeholder" to "E.g., 100",
            "products_avail" to "📦 Decentralized Products Ledger",
            "merchant_verified" to "Verified Partner",
            "merchant_under_surv" to "Under AI Observation",
            "buy_retail" to "Retail (مفرق)",
            "buy_wholesale" to "Wholesale (جملة)",
            "quantity" to "Quantity:",
            "place_order" to "Place Deal & Order 🚀",
            "view_ingredients" to "Chem Ingredients Report 🔬",
            "my_basket" to "🛍️ Active Distributed Orders Ledger",
            "saved_products" to "⭐ Guarded Bookmarked Products",
            "merchant_source" to "📍 Merchant source: ",
            "retail_label" to "Retail Price (المفرق):",
            "wholesale_label" to "Wholesale Carton Price (الجملة طرد):",
            "order_mode" to "Order Mode:",
            "align_mismatch" to "Align Content & Solve Mismatches ⚡",
            "stock_left" to "Stock Left: ",
            "units" to " units",
            "run_benchmark" to "Run Market Benchmark ⚖️",
            "gen_ad" to "Generate Ad Overlay 🎨",
            "driver_safety" to "Driver Safety Index Rate:",
            "fuel_saved" to "Fuel Saved (This Month):",
            "est_score" to "Est. Navigation Performance Score:",
            "no_delivery" to "No active delivery tasks allocated. Wait for systems assignment...",
            "unassigned_orders" to "🚚 Unassigned Physical Orders Carousel",
            "assigned_active" to "📍 Your Assigned Active Delivery Routes",
            "id" to "Order ID: #",
            "product" to "Product: ",
            "route_matrix" to "Fast Route Matrix 🎯",
            "mark_delivered" to "Mark Delivered ✔",
            "accept_carriage" to "Accept Carriage 🚚",
            "metrics" to "📊 Platform-Wide Ledger Metrics",
            "total_users" to "Total Users Registered:",
            "active_sales" to "Active Direct Sales Transactions:",
            "commission_opt" to "Dynamic Commission Rate Optimization:",
            "recalc_opt" to "Recalculate AI Optimization",
            "dispute_resol" to "⚖️ Automated Multi-Party Dispute Arbitration",
            "dispute_topic" to "Dispute Topic (موضوع الخلاف)",
            "cust_complaint" to "Customer Statement/Complaint (شكوى العميل)",
            "merch_defense" to "Merchant Defence Statement (دفاع التاجر)",
            "run_arbitration" to "Run AI Arbitration Trial ⚡",
            "registered_users" to "👥 Platform Registered Users List",
            "no_users" to "No users registered in private ledger yet.",
            "contact_phone" to "📞 Contact Phone: ",
            "email_ledger" to "📧 Email Ledger: ",
            "behavior_opt" to "Behavior Opt-in: ",
            "enrolled" to "Enrolled (Yes)",
            "declined" to "Declined (No)",
            "success_order" to "Order placed successfully! Total: $",
            "no_matching_prod" to "No matching products found.",
            "budget_ok" to "Smart budget filtering applied! We found products fitting under your threshold.",
            "excel_aligned" to "Successfully parsed Excel inventory manifest. System has auto-aligned quantities and resolved discrepancies with 0% error rate.",
            "benchmark_result" to "Competitive benchmark analysis finished. Your product pricing is optimal with a 15% better turnover margin than the region average.",
            "banner_ad_result" to "Perfect optimized social media promotional canvas generated successfully!",
            "dispute_arbitrated" to "AI Arbitrator verdict issued: Neutral distribution of fault, recommended 50% partial refund.",
            "lang_en" to "English",
            "lang_ar" to "العربية",
            "change_lang" to "Language (اللغة)"
        ),
        "ar" to mapOf(
            "app_title" to "أسواق جوافة",
            "app_subtitle" to "متجر المواد الغذائية الطازجة والعضوية الممتازة",
            "app_description" to "تسوق خضروات وفواكه طازجة بأفضل الأسعار بالذكاء الاصطناعي",
            "sign_up_tab" to "إنشاء حساب (Sign Up)",
            "sign_in_tab" to "تسجيل دخول (Sign In)",
            "create_account" to "إنشاء حساب جديد",
            "full_name" to "الاسم الكامل",
            "phone_num" to "رقم الهاتف",
            "email_addr" to "البريد الإلكتروني",
            "select_role" to "اختر وظيفتك:",
            "role_customer" to "زبون",
            "role_merchant" to "تاجر",
            "role_delivery" to "سائق توصيل",
            "role_admin" to "مسؤول المنصة",
            "request_code" to "طلب رمز الدخول الذكي 🔑",
            "google_signup" to "التسجيل من خلال جوجل",
            "sign_in_title" to "تسجيل الدخول إلى بيئة العمل الخاص بك",
            "enter_email_phone" to "البريد الإلكتروني أو رقم الهاتف",
            "password" to "كلمة المرور",
            "access_platform" to "الدخول الآمن للمنصة 🔑",
            "quick_fill" to "اضغط هنا لتعبئة بيانات المدير الافتراضية تلقائياً",
            "shield_sec" to "تم التحقق من حماية وحصانة المنصة",
            "otp_msg" to "تم تكوين رمز مرور لمرة واحدة (OTP) فريد مكون من 6 أرقام بواسطة مصفوفة أمن المنصة وإرساله إلى بريدك أو هاتفك.",
            "secret_msg" to "🔑 مفتاح الدخول السري المولد: ",
            "six_digit" to "أدخل الرمز المكون من 6 أرقام",
            "back" to "رجوع",
            "confirm_access" to "تأكيد الدخول ✔",
            "select_google_acc" to "اختر حساب جوجل للمتابعة والربط",
            "google_picker_desc" to "يرجى تحديد بريد جوجل النشط المرتبط بجهازك لتأمين الدخول باستخدام تكامل مصادقة جوجل:",
            "google_consent_title" to "الموافقة على صلاحيات حساب جوجل",
            "google_consent_desc" to "يطلب تطبيق متجر الذكاء الاصطناعي (AI Store) الوصول للمعلومات التالية لتأمين الحساب:",
            "google_consent_bullets" to "• التحقق من بريدك الإلكتروني الأساسي على جوجل\n• مزامنة الاسم المعتمد وصورة الملف الشخصي\n• منح أذونات آمنة لحفظ عمليات التسوق والطلبات",
            "google_consent_note" to "بالموافقة، سيقوم نظام جوجل بمنح الترخيص الآمن لتسجيل دخولك بأمان.",
            "approve_connect" to "الموافقة والربط 🚀",
            "deny" to "رفض",
            "cancel" to "إلغاء الأمر",
            "hi" to "مرحباً، ",
            "logout" to "نشاط الخروج",
            "ai_core" to " مصفوفة محرك الذكاء الاصطناعي نشطة الان",
            "ai_idle" to "محرك الذكاء الاصطناعي بانتظارك. قم بإجراء بحث، مطابقة أسعار، محاذاة المخازن أو تحكيم لحل النزاعات لتشغيل المنظومة...",
            "workspace_customer" to "بوابة المشتري الذكية (Customer Workspace)",
            "workspace_merchant" to "بوابة التاجر الذكية (Merchant AI Engine)",
            "workspace_delivery" to "بوابة السائق وتحسين اللوجستيات (Logistics Engine)",
            "workspace_admin" to "لوحة تحكم مالك المنصة (Platform Control)",
            "customer_search_title" to "🔍 البحث والمقارنة المرئية الفورية",
            "customer_search_desc" to "قم بتصوير أو كتابة اسم المنتج. ليقوم محرك الذكاء الاصطناعي فوراً بالبحث في منصات التواصل والمقارنة بين سعر التجزئة وسعر الجملة.",
            "search_placeholder" to "مثال: عسل جبلي طبيعي، قهوة تركية...",
            "map_budget_btn" to "تحديد الميزانية الذكية 💸",
            "budget_placeholder" to "أقصى ميزانية بالدولار - مثال: 100",
            "products_avail" to "📦 سجل المنتجات اللامركزي المتاح للبيع",
            "merchant_verified" to "شريك موثق ومعتمد",
            "merchant_under_surv" to "تحت مراقبة الذكاء الاصطناعي المستمرة",
            "buy_retail" to "تجزئة (مفرق)",
            "buy_wholesale" to "جملة (بالطرد في الكرتونة)",
            "quantity" to "الكمية المطلوبة:",
            "place_order" to "إبرام الصفقة وتأكيد الشراء 🚀",
            "view_ingredients" to "تقرير التحليل الكيميائي للمكونات 🔬",
            "my_basket" to "🛍️ دفتر مشترياتي وطلباتي النشطة",
            "saved_products" to "⭐ المنتجات المحفوظة في المفضلة",
            "merchant_source" to "📍 مصدر منتج التاجر: ",
            "retail_label" to "سعر المفرق (تجزئة):",
            "wholesale_label" to "سعر طرد الجملة:",
            "order_mode" to "طريقة الشراء المحددة:",
            "align_mismatch" to "محاذاة المخزون وحل التناقضات كليا ⚡",
            "stock_left" to "الكمية المتبقية في المخزن: ",
            "units" to " وحدة",
            "run_benchmark" to "تشغيل محاكاة مقارنة الأسعار بالسوق ⚖️",
            "gen_ad" to "توليد تصميم إعلاني ذكي للمنتج 🎨",
            "driver_safety" to "معدل مؤشر السلامة والأمان للسائق:",
            "fuel_saved" to "الوقود الموفر (هذا الشهر):",
            "est_score" to "درجة أداء الملاحة المسجلة بالكامل:",
            "no_delivery" to "لا توجد مهام توصيل نشطة حالياً. انتظر حتى يقوم النظام بتخصيص شحنة جديدة...",
            "unassigned_orders" to "🚚 الشحنات الفعلية الجاهزة للتوصيل والتحميل",
            "assigned_active" to "📍 مسارات التوصيل والخرائط المعطاة لك",
            "id" to "رقم الطلبية السري: #",
            "product" to "المنتج: ",
            "route_matrix" to "خارطة المسار الفائق السرعة 🎯",
            "mark_delivered" to "التعليم كمكتمل ومسلم بنجاح ✔",
            "accept_carriage" to "قبول وتحميل الشحنة فوراً 🚚",
            "metrics" to "📊 مؤشرات وسجلات أداء بيئة المنصة الشاملة",
            "total_users" to "إجمالي المستخدمين المسجلين في النظام الآمن:",
            "active_sales" to "عمليات بيع وشراء حقيقية نشطة:",
            "commission_opt" to "معدل العمولات الديناميكي والأرباح:",
            "recalc_opt" to "إعادة حساب وتحسين معدل الأرباح",
            "dispute_resol" to "⚖️ التحكيم الآلي في النزاعات لجميع الأطراف المعنية",
            "dispute_topic" to "موضوع الخلاف ونوع المشكلة",
            "cust_complaint" to "تصريح شكوى العميل واعتراضه المفصل",
            "merch_defense" to "بيان دفاع التاجر والرد على الشكوى",
            "run_arbitration" to "بدء محاكمة التحكيم الذاتي للذكاء الاصطناعي ⚡",
            "registered_users" to "👥 سجل المستخدمين المسجلين بالمنصة",
            "no_users" to "لا يوجد أي مستخدمين مسجلين في الدفتر الآمن بعد.",
            "contact_phone" to "📞 هاتف التواصل المعين: ",
            "email_ledger" to "📧 البريد الإلكتروني الخاص: ",
            "behavior_opt" to "الموافقة السلوكية: ",
            "enrolled" to "منخرط ومشارك (نعم)",
            "declined" to "غير منخرط ومرفوض (لا)",
            "success_order" to "تم إبرام الصفقة وتأكيد طلبك بنجاح! الإجمالي: $",
            "no_matching_prod" to "لم يتم العثور على أي منتجات مطابقة للبحث.",
            "budget_ok" to "تم تطبيق تصفية الميزانية الذكية بنجاح! وجدنا خيارات تناسب السقف المالي المحدد.",
            "excel_aligned" to "تمت قراءة وفك شفرة قائمة مخزن Excel بنجاح. قام النظام بمواءمة وتصحيح الفروقات للمنتجات بمعدل خطأ 0%.",
            "benchmark_result" to "انتهت المقارنة التنافسية لأسعار التاجر. تسعيرك الحالي ممتاز ولديك هامش ربح أعلى بنسبة 15% من متوسط الأسعار بالمنطقة.",
            "banner_ad_result" to "تم توليد وتصميم واجهة ترويجية تسويقية مثالية وجذابة لوسائل التواصل الاجتماعي بنجاح!",
            "dispute_arbitrated" to "صدر حكم المحكم الآلي: تقرر توزيع الخطأ بالتساوي بين الطرفين، ويقترح استرجاع جزئي للمشتري بنسبة 50%.",
            "lang_en" to "English",
            "lang_ar" to "العربية",
            "change_lang" to "تغيير اللغة (Change Language)"
        )
    )

    fun get(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}

@Composable
fun stringResource(key: String, viewModel: MarketViewModel): String {
    val lang by viewModel.appLanguage.collectAsState()
    return Localization.get(key, lang)
}
